version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: task_notifications
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: adminadmin
      MYSQL_DATABASE: task_notifications
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: sh -c "until nc -z mysql 3306; do echo Waiting for MySQL; sleep 2; done; npm start"

volumes:
  mysql-data:
